name: autobuild
on:
    push:
        branches:
        - "*"
    workflow_dispatch:
  
jobs:
    bun-install-and-dev:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            fetch-depth: 0 # Ensure all history is fetched for commits

        - name: Set up Bun
          run: |
            curl -fsSL https://bun.sh/install | bash
            echo "export PATH=\"$HOME/.bun/bin:$PATH\"" >> $GITHUB_ENV

        - name: Install dependencies with Bun
          run: ~/.bun/bin/bun install

        - name: Run build
          run: ~/.bun/bin/bun run build

        - name: Commit and push changes
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            git config --global user.name "github-actions[bot]"
            git config --global user.email "github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Run bun install and dev script changes" || echo "No changes to commit"
            git push origin HEAD